### ISSUE TITLE
CatmullRom Curve disappears when exactly 3 values are passed

### ISSUE THREAD

**Issue by ondrejsevcik** [gampleman/elm-visualization#38]
Hi, when I try to render line with less than 4 values, it doesn't render line. Is that intended or is it a bug? 

He is minimalistic ellie reproduction https://ellie-app.com/3MLF4BVzDPKa1

Thanks 🙏

**Comment by gampleman** [comment]
The catmulrom curve is defined for 2, and 4+ points. Seems like three is perhaps an oversight. 

/cc @folkertdev

**Comment by folkertdev** [comment]
Yea, it seems to function fine still when three points are allowed. 

I think I got something mixed up when translating [this (not very readable) D3 code](https://github.com/d3/d3-shape/blob/master/src/curve/catmullRom.js#L63). But if i'm reading it correctly now, it will actually not draw anything for 2 points. Is that desirable? drawing a straight line seems like a better default in that case. Thoughs? 

At the moment the open catmull-rom requires 3 or more points (which makes sense, because the first and final point are not actually touched at all with this interpolation) and the closed catmull-rom accepts 2 or more points.

**Comment by folkertdev** [comment]
This bug has been fixed in the latest version of one-true-path-experiment [4.0.2](https://github.com/folkertdev/one-true-path-experiment/releases/tag/4.0.2)

**Comment by gampleman** [comment]
So I assume if one reinstalls elm-visualization from scratch they should get the new version, right?

**Comment by ondrejsevcik** [comment]
I deleted `elm-stuff` and `~/.elm` folders but when I run app I still got the old version. I had to manually upgrade version in `elm.json`.
